In [9]:
from sklearn.neural_network import MLPClassifier
import pandas as pd
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', sep=',',header=None)
df.values
data = df.values[:,0:4]
target = df.values[:,4]

for i in range(0,len(target)):
    if(target[i] == 'Iris-setosa'):
        target[i] = 1
    elif(target[i] == 'Iris-versicolor'):
        target[i] = 2
    elif(target[i] == 'Iris-virginica'):
        target[i] = 3
    else:
        print('Target index: ', i, ' Not Handled! Value: ', target[i])
        

import numpy as np
from sklearn.model_selection import train_test_split
data_training, data_testing, target_training1, target_testing1 = train_test_split(data, target, test_size=0.33, random_state=42)

i = 0
target_training = []
while i < len(target_training1):
    x = target_training1[i]
    target_training.append(x)
    i = i + 1

i = 0
target_testing = []
while i < len(target_testing1):
    x = target_testing1[i]
    target_testing.append(x)
    i = i + 1

clf = MLPClassifier(solver='lbfgs'
                   , alpha=1e-5
                   , hidden_layer_sizes=(15,)
                   , random_state=1
                   )
clf.fit(data_training, target_training)
print(clf)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(15,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)


In [10]:
results = clf.predict(data_testing)
print(results)
resultsLength = len(results)
for i in range(0,len(data_testing)):
    print(data_testing[i], ' = ', target_testing[i], ' results = ', results[i])
j = 0
for i in range (0, resultsLength):
    if(results[i] == target_testing[i]):
        j = j + 1
        
print('Accuracy = ', (j/resultsLength)*100, '%')


[2 1 3 2 2 1 2 3 2 2 3 1 1 1 1 2 3 2 2 3 1 3 1 3 3 3 3 3 1 1 1 1 2 1 1 3 2
 1 1 1 3 2 2 1 1 2 2 3 2 3]
[6.1 2.8 4.7 1.2]  =  2  results =  2
[5.7 3.8 1.7 0.3]  =  1  results =  1
[7.7 2.6 6.9 2.3]  =  3  results =  3
[6.0 2.9 4.5 1.5]  =  2  results =  2
[6.8 2.8 4.8 1.4]  =  2  results =  2
[5.4 3.4 1.5 0.4]  =  1  results =  1
[5.6 2.9 3.6 1.3]  =  2  results =  2
[6.9 3.1 5.1 2.3]  =  3  results =  3
[6.2 2.2 4.5 1.5]  =  2  results =  2
[5.8 2.7 3.9 1.2]  =  2  results =  2
[6.5 3.2 5.1 2.0]  =  3  results =  3
[4.8 3.0 1.4 0.1]  =  1  results =  1
[5.5 3.5 1.3 0.2]  =  1  results =  1
[4.9 3.1 1.5 0.1]  =  1  results =  1
[5.1 3.8 1.5 0.3]  =  1  results =  1
[6.3 3.3 4.7 1.6]  =  2  results =  2
[6.5 3.0 5.8 2.2]  =  3  results =  3
[5.6 2.5 3.9 1.1]  =  2  results =  2
[5.7 2.8 4.5 1.3]  =  2  results =  2
[6.4 2.8 5.6 2.2]  =  3  results =  3
[4.7 3.2 1.6 0.2]  =  1  results =  1
[6.1 3.0 4.9 1.8]  =  3  results =  3
[5.0 3.4 1.6 0.4]  =  1  results =  1
[6.4 2.8 5.6 2.1]  =  3